# Generated by Django 6.1 on 2026-10-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransReview',
        ),
    ]
