# Generated by Django 6.1 on 2026-10-05 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_delete_transreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectorlist',
            options={'ordering': ['code'], 'verbose_name': '板块列表', 'verbose_name_plural': '板块列表'},
        ),
        migrations.AlterModelOptions(
            name='stocklist',
            options={'ordering': ['code'], 'verbose_name': '股票列表', 'verbose_name_plural': '股票列表'},
        ),
        migrations.AlterModelOptions(
            name='stocksector',
            options={'ordering': ['stock_code'], 'verbose_name': '板块关联', 'verbose_name_plural': '板块关联'},
        ),
        migrations.AlterModelOptions(
            name='websetting',
            options={'ordering': ['id', 'group_name', 'sort_order'], 'verbose_name': '网站配置', 'verbose_name_plural': '网站配置'},
        ),
        migrations.AlterField(
            model_name='focushistory',
            name='win_ratio',
            field=models.IntegerField(default=0, verbose_name='盈利概率'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='win_ratio',
            field=models.IntegerField(default=0, verbose_name='盈利概率'),
        ),
    ]
