# Generated by Django 6.1 on 2026-10-05 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_alter_sectorlist_options_alter_stocklist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filterconfig',
            table='models_filter_config',
        ),
    ]
