# Generated by Django 6.1 on 2026-08-17 21:46

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, default=100000, max_digits=14, verbose_name='总资金')),
                ('cash', models.DecimalField(decimal_places=2, default=100000, max_digits=14, verbose_name='现金')),
                ('stock', models.DecimalField(decimal_places=2, default=100000, max_digits=14, verbose_name='股票')),
                ('available', models.DecimalField(decimal_places=2, default=100000, max_digits=14, verbose_name='可用资金')),
                ('commission_ratio', models.DecimalField(decimal_places=5, default=Decimal('0.00025'), max_digits=8, verbose_name='佣金费率')),
                ('commission_min', models.DecimalField(decimal_places=2, default=Decimal('5'), max_digits=8, verbose_name='最低佣金')),
                ('stamp_buy_ratio', models.DecimalField(decimal_places=5, default=Decimal('0.0005'), max_digits=8, verbose_name='印花税率(买入)')),
                ('stamp_sell_ratio', models.DecimalField(decimal_places=5, default=Decimal('0.0005'), max_digits=8, verbose_name='印花税率(卖出)')),
                ('lot_size', models.IntegerField(default=100, verbose_name='每手股数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '资金配置',
                'verbose_name_plural': '资金配置',
                'db_table': 'models_cash_config',
            },
        ),
        migrations.CreateModel(
            name='StockList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='如 601398', max_length=20, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('market', models.CharField(default='SH', max_length=10, verbose_name='市场')),
                ('industry', models.CharField(max_length=50, verbose_name='行业')),
            ],
            options={
                'verbose_name': '股票列表',
                'verbose_name_plural': '股票列表',
                'db_table': 'models_stock_list',
            },
        ),
        migrations.CreateModel(
            name='FocusStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='如 601398', max_length=20, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('market', models.CharField(default='SH', max_length=10, verbose_name='市场')),
                ('cat', models.CharField(default='stock', max_length=10, verbose_name='类型')),
                ('focus_date', models.DateField(default=django.utils.timezone.now, verbose_name='关注日期')),
                ('plan_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='计划填报')),
                ('plan_qty', models.IntegerField(default=0, verbose_name='计划数量')),
                ('target_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='目标价格')),
                ('stop_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='止损价格')),
                ('allowed_qty', models.IntegerField(default=0, verbose_name='允许数量')),
                ('win_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='胜率')),
                ('status', models.CharField(choices=[('watching', '关注中'), ('closed', '已关闭')], db_index=True, default='watching', max_length=10, verbose_name='状态')),
                ('close_date', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('close_reason', models.CharField(blank=True, choices=[('manual', '手动关闭'), ('bought', '已买入')], default='', max_length=20, verbose_name='关闭原因')),
                ('sort_order', models.IntegerField(default=0, help_text='手动排序，越小越靠前', verbose_name='排序')),
                ('comments', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '关注股票',
                'verbose_name_plural': '关注股票',
                'db_table': 'models_focus_stock',
                'ordering': ['sort_order', '-focus_date'],
                'indexes': [models.Index(fields=['code', 'status'], name='models_focu_code_cbd41e_idx')],
            },
        ),
        migrations.CreateModel(
            name='FocusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '创建关注'), ('edit', '调整计划'), ('close', '关闭关注'), ('buy', '已买入')], default='edit', max_length=10, verbose_name='操作')),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='操作时间')),
                ('plan_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='计划买入价')),
                ('plan_qty', models.IntegerField(default=0, verbose_name='计划买入量')),
                ('target_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='目标价')),
                ('stop_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='止损价')),
                ('win_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='胜率')),
                ('comments', models.TextField(blank=True, default='', verbose_name='备注')),
                ('focus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='models.focusstock', verbose_name='关联关注')),
            ],
            options={
                'verbose_name': '关注历史',
                'verbose_name_plural': '关注历史',
                'db_table': 'models_focus_history',
                'ordering': ['-edit_date'],
            },
        ),
        migrations.CreateModel(
            name='TransOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('market', models.CharField(default='SH', max_length=10, verbose_name='市场')),
                ('cat', models.CharField(default='stock', max_length=10, verbose_name='类型')),
                ('status', models.CharField(choices=[('open', '持仓中'), ('closed', '已平仓')], db_index=True, default='open', max_length=10, verbose_name='状态')),
                ('target_price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='目标价')),
                ('stop_price', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='止损价')),
                ('open_date', models.DateTimeField(blank=True, null=True, verbose_name='建仓时间')),
                ('close_date', models.DateTimeField(blank=True, null=True, verbose_name='平仓时间')),
                ('buy_qty', models.IntegerField(default=0, verbose_name='累计买入数量')),
                ('sell_qty', models.IntegerField(default=0, verbose_name='累计卖出数量')),
                ('buy_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='累计买入金额')),
                ('sell_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='累计卖出金额')),
                ('buy_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累计买入费用')),
                ('sell_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='累计卖出费用')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='费用总计')),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='盈利')),
                ('comments', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('focus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='models.focusstock', verbose_name='关联关注')),
            ],
            options={
                'verbose_name': '交易订单',
                'verbose_name_plural': '交易订单',
                'db_table': 'models_trans_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('L', '买入'), ('S', '卖出')], max_length=1, verbose_name='交易方向')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='成交日期')),
                ('price', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='成交价格')),
                ('qty', models.IntegerField(verbose_name='成交数量')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='成交金额')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='成交费用')),
                ('comments', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='models.transorder', verbose_name='所属交易')),
            ],
            options={
                'verbose_name': '成交明细',
                'verbose_name_plural': '成交明细',
                'db_table': 'models_trans_deal',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TransReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', verbose_name='复盘内容')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='评分(1-5)')),
                ('comments', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('focus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='models.focusstock', verbose_name='关联关注')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='models.transorder', verbose_name='关联交易')),
            ],
            options={
                'verbose_name': '复盘记录',
                'verbose_name_plural': '复盘记录',
                'db_table': 'models_trans_review',
                'ordering': ['-updated_at'],
            },
        ),
    ]
