# Generated by Django 6.1 on 2026-08-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transreview',
            name='content',
        ),
        migrations.AlterField(
            model_name='focushistory',
            name='plan_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='计划填报'),
        ),
        migrations.AlterField(
            model_name='focushistory',
            name='plan_qty',
            field=models.IntegerField(default=0, verbose_name='计划数量'),
        ),
        migrations.AlterField(
            model_name='focushistory',
            name='stop_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='止损价格'),
        ),
        migrations.AlterField(
            model_name='focushistory',
            name='target_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='目标价格'),
        ),
        migrations.AlterField(
            model_name='focushistory',
            name='win_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='盈利概率'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='cat',
            field=models.CharField(default='stock', max_length=10, verbose_name='股票类型'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='code',
            field=models.CharField(db_index=True, help_text='如 601398', max_length=20, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='market',
            field=models.CharField(default='SH', max_length=10, verbose_name='股票市场'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='name',
            field=models.CharField(max_length=50, verbose_name='股票名称'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='win_ratio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='盈利概率'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='cat',
            field=models.CharField(default='stock', max_length=10, verbose_name='股票类型'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='market',
            field=models.CharField(default='SH', max_length=10, verbose_name='股票市场'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='name',
            field=models.CharField(max_length=50, verbose_name='股票名称'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='盈利金额'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='status',
            field=models.CharField(choices=[('open', '持仓中'), ('closed', '已平仓')], db_index=True, default='open', max_length=10, verbose_name='交易状态'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='stop_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='止损价格'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='target_price',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='目标价格'),
        ),
        migrations.AlterField(
            model_name='transreview',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='评分'),
        ),
    ]
