# Generated by Django 6.1 on 2026-09-28 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transhistory',
            name='dividend_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='分红金额'),
        ),
        migrations.AddField(
            model_name='transhistory',
            name='dividend_tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='红利税'),
        ),
    ]
