# Generated by Django 6.1 on 2026-10-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlist',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, '优'), (2, '良'), (3, '中'), (4, '差')], null=True, verbose_name='评级'),
        ),
    ]
