# Generated by Django 6.1 on 2026-09-27 12:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='transfer_fee_bj',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00001'), max_digits=8, verbose_name='过户费(北交所)'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='transfer_fee_sh',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00001'), max_digits=8, verbose_name='过户费(沪市)'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='transfer_fee_sz',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00001'), max_digits=8, verbose_name='过户费(深市)'),
        ),
    ]
