# Generated by Django 6.1 on 2026-09-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='remark',
            field=models.CharField(default='', max_length=200, verbose_name='说明'),
        ),
    ]
