# Generated by Django 6.1 on 2026-10-04 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cashhistory',
            options={'ordering': ['-id'], 'verbose_name': '资金历史', 'verbose_name_plural': '资金历史'},
        ),
        migrations.AlterField(
            model_name='dividendrecord',
            name='dividend_type',
            field=models.CharField(choices=[('cash', '分红'), ('bonus', '送股')], default='cash', max_length=10, verbose_name='分红类型'),
        ),
    ]
