# Generated by Django 6.1 on 2026-08-18 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_remove_transreview_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='focushistory',
            name='intent',
            field=models.CharField(choices=[('L', '买入'), ('S', '卖出')], default='L', max_length=1, verbose_name='交易方向'),
        ),
        migrations.AddField(
            model_name='focusstock',
            name='intent',
            field=models.CharField(choices=[('L', '买入'), ('S', '卖出')], default='L', max_length=1, verbose_name='交易方向'),
        ),
        migrations.AlterField(
            model_name='focushistory',
            name='action',
            field=models.CharField(choices=[('create', '创建关注'), ('edit', '调整计划'), ('close', '关闭关注'), ('deal', '已交易')], default='edit', max_length=10, verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='transdeal',
            name='intent',
            field=models.CharField(choices=[('L', '买入'), ('S', '卖出')], default='S', max_length=1, verbose_name='交易方向'),
        ),
    ]
