# Generated by Django 6.1 on 2026-09-28 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_transhistory_dividend_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashhistory',
            name='event',
            field=models.CharField(choices=[('deposit', '存入资金'), ('withdraw', '取出资金'), ('buy', '买入股票'), ('sell', '卖出股票'), ('dividend', '股票分红'), ('adjust', '调整计划')], default='deposit', max_length=20, verbose_name='事项'),
        ),
    ]
