# Generated by Django 6.1 on 2026-09-27 13:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_websetting_transfer_fee_bj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterglobalconfig',
            name='filter_timeout',
            field=models.IntegerField(default=3600, verbose_name='筛选超时时间(秒)'),
        ),
        migrations.AddField(
            model_name='filterglobalconfig',
            name='stop_loss_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.98'), max_digits=5, verbose_name='添加关注止损价'),
        ),
        migrations.AddField(
            model_name='filterglobalconfig',
            name='target_profit_ratio',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.1'), max_digits=5, verbose_name='添加关注目标价'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='default_page_size',
            field=models.IntegerField(default=10, verbose_name='每页默认数量'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_ema_d_day',
            field=models.IntegerField(default=30, verbose_name='日线EMA-D值'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_ema_d_month',
            field=models.IntegerField(default=30, verbose_name='月线EMA-D值'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_ema_d_week',
            field=models.IntegerField(default=30, verbose_name='周线EMA-D值'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_ema_k_day',
            field=models.IntegerField(default=10, verbose_name='日线EMA-K值'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_ema_k_month',
            field=models.IntegerField(default=20, verbose_name='月线EMA-K值'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_ema_k_week',
            field=models.IntegerField(default=20, verbose_name='周线EMA-K值'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_ma_day',
            field=models.IntegerField(default=200, verbose_name='日线MA周期'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_ma_month',
            field=models.IntegerField(default=30, verbose_name='月线MA周期'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_ma_week',
            field=models.IntegerField(default=60, verbose_name='周线MA周期'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_mv_day',
            field=models.IntegerField(default=60, verbose_name='日线MV周期'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_mv_month',
            field=models.IntegerField(default=30, verbose_name='月线MV周期'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_mv_week',
            field=models.IntegerField(default=30, verbose_name='周线MV周期'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_start_date_day',
            field=models.CharField(default='19801020', max_length=8, verbose_name='日线起始日期'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_start_date_month',
            field=models.CharField(default='19801020', max_length=8, verbose_name='月线起始日期'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_start_date_week',
            field=models.CharField(default='19801020', max_length=8, verbose_name='周线起始日期'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='quote_interval',
            field=models.IntegerField(default=60000, verbose_name='行情刷新间隔(毫秒)'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='trade_am_end',
            field=models.IntegerField(default=41400, verbose_name='上午结束时间'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='trade_am_start',
            field=models.IntegerField(default=34200, verbose_name='上午开始时间'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='trade_pm_end',
            field=models.IntegerField(default=54000, verbose_name='下午结束时间'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='trade_pm_start',
            field=models.IntegerField(default=46800, verbose_name='下午开始时间'),
        ),
    ]
