# Generated by Django 6.1 on 2026-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_filterglobalconfig_filter_timeout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='icp_number',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='备案编号'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='icp_website',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='备案官网'),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='default_page_size',
            field=models.IntegerField(default=10, verbose_name='分页默认数量'),
        ),
    ]
