# Generated by Django 6.1 on 2026-08-19 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_focushistory_intent_focusstock_intent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focushistory',
            name='intent',
            field=models.CharField(choices=[('B', '买入'), ('S', '卖出')], default='B', max_length=1, verbose_name='交易方向'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='intent',
            field=models.CharField(choices=[('B', '买入'), ('S', '卖出')], default='B', max_length=1, verbose_name='交易方向'),
        ),
        migrations.AlterField(
            model_name='transdeal',
            name='intent',
            field=models.CharField(choices=[('B', '买入'), ('S', '卖出')], default='S', max_length=1, verbose_name='交易方向'),
        ),
    ]
