# Generated by Django 6.1 on 2026-08-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_alter_focushistory_intent_alter_focusstock_intent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashconfig',
            name='lot_size',
        ),
    ]
