# Generated by Django 6.1 on 2026-09-27 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_websetting_icp_number_websetting_icp_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='density_max',
            field=models.IntegerField(default=20, verbose_name='K线最大密度'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='density_min',
            field=models.IntegerField(default=5, verbose_name='K线最小密度'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='density_std',
            field=models.IntegerField(default=13, verbose_name='K线标准密度'),
        ),
    ]
