# Generated by Django 6.1 on 2026-09-27 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_websetting_density_max_websetting_density_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='bp1',
            field=models.IntegerField(default=1200, verbose_name='断点一'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='bp2',
            field=models.IntegerField(default=1440, verbose_name='断点二'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='bp3',
            field=models.IntegerField(default=1920, verbose_name='断点三'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='cash_chart_height',
            field=models.IntegerField(default=400, verbose_name='资金曲线高度'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='chart_placeholder_height',
            field=models.IntegerField(default=400, verbose_name='图表最小高度'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='gap_height',
            field=models.IntegerField(default=2, verbose_name='导航间隔'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='h1',
            field=models.IntegerField(default=100, verbose_name='高度一'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='h2',
            field=models.IntegerField(default=90, verbose_name='高度二'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='h3',
            field=models.IntegerField(default=80, verbose_name='高度三'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='h4',
            field=models.IntegerField(default=75, verbose_name='高度四'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='kline_main_ratio',
            field=models.IntegerField(default=80, verbose_name='K线主图比例'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='mobile_breakpoint',
            field=models.IntegerField(default=992, verbose_name='移动断点'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='nav_height',
            field=models.IntegerField(default=50, verbose_name='导航高度（桌面）'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='nav_height_mobile',
            field=models.IntegerField(default=40, verbose_name='导航高度（移动）'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='nav_locked',
            field=models.BooleanField(default=False, verbose_name='锁定导航栏'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='navi_bar_height',
            field=models.IntegerField(default=25, verbose_name='底部导航高度'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='screen_height_threshold',
            field=models.IntegerField(default=800, verbose_name='高度阈值'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='trend_main_ratio',
            field=models.IntegerField(default=75, verbose_name='分时主图比例'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='w1',
            field=models.IntegerField(default=100, verbose_name='页面宽度一'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='w2',
            field=models.IntegerField(default=85, verbose_name='页面宽度二'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='w3',
            field=models.IntegerField(default=70, verbose_name='页面宽度三'),
        ),
        migrations.AddField(
            model_name='websetting',
            name='w4',
            field=models.IntegerField(default=60, verbose_name='页面宽度四'),
        ),
    ]
