# Generated by Django 6.1 on 2026-08-21 17:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_remove_cashconfig_lot_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='变化日期')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='总资金')),
                ('cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='现金')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='股票市值')),
                ('reason', models.CharField(choices=[('deposit', '存入资金'), ('withdraw', '取出资金'), ('buy', '买入股票'), ('sell', '卖出股票'), ('adjust', '手动调整'), ('dividend', '分红')], default='adjust', max_length=20, verbose_name='变化原因')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='正数=增加, 负数=减少', max_digits=14, verbose_name='变化金额')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_histories', to='models.transorder', verbose_name='关联交易')),
            ],
            options={
                'verbose_name': '资金历史',
                'verbose_name_plural': '资金历史',
                'db_table': 'models_cash_history',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
