# Generated by Django 6.1 on 2026-08-30 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0006_cashhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusstock',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
    ]
