# Generated by Django 6.1 on 2026-08-30 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0007_alter_focusstock_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusstock',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
