# Generated by Django 6.1 on 2026-08-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_alter_focusstock_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklist',
            name='cat',
            field=models.CharField(default='stock', max_length=10, verbose_name='类别'),
        ),
    ]
