# Generated by Django 6.1 on 2026-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_stocklist_cat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='如 601398', max_length=20, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='板块')),
                ('market', models.CharField(default='SH', max_length=10, verbose_name='市场')),
                ('cat', models.CharField(default='SI', max_length=10, verbose_name='类别')),
                ('mark', models.CharField(max_length=50, verbose_name='行业')),
            ],
            options={
                'verbose_name': '板块列表',
                'verbose_name_plural': '板块列表',
                'db_table': 'models_secotr_list',
            },
        ),
    ]
