# Generated by Django 6.1 on 2026-09-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0010_sectorlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorlist',
            name='market',
            field=models.CharField(default='', max_length=10, verbose_name='市场'),
        ),
    ]
