# Generated by Django 6.1 on 2026-09-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0011_alter_sectorlist_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorlist',
            name='mark',
            field=models.CharField(max_length=50, verbose_name='标记'),
        ),
    ]
