# Generated by Django 6.1 on 2026-09-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0012_alter_sectorlist_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorlist',
            name='market',
            field=models.CharField(default='L1', max_length=10, verbose_name='市场'),
        ),
    ]
