# Generated by Django 6.1 on 2026-09-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0013_alter_sectorlist_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusstock',
            name='code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='股票代码'),
        ),
        migrations.AlterField(
            model_name='sectorlist',
            name='code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='代码'),
        ),
        migrations.AlterField(
            model_name='stocklist',
            name='code',
            field=models.CharField(db_index=True, max_length=20, verbose_name='代码'),
        ),
    ]
