# Generated by Django 6.1 on 2026-09-06 16:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0014_alter_focusstock_code_alter_sectorlist_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashconfig',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='cashhistory',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='focushistory',
            name='edit_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='操作日期'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='关闭日期'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='updated_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='transdeal',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='close_date',
            field=models.DateField(blank=True, null=True, verbose_name='平仓日期'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='open_date',
            field=models.DateField(blank=True, null=True, verbose_name='建仓日期'),
        ),
        migrations.AlterField(
            model_name='transorder',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
        migrations.AlterField(
            model_name='transreview',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='transreview',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
