# Generated by Django 6.1 on 2026-09-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0015_alter_cashconfig_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='focusstock',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='updated_at',
            field=models.DateField(auto_now=True, verbose_name='更新日期'),
        ),
    ]
