# Generated by Django 6.1 on 2026-09-06 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0016_alter_focusstock_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorlist',
            name='hide',
            field=models.CharField(default='', max_length=50, verbose_name='隐藏'),
        ),
        migrations.AlterField(
            model_name='sectorlist',
            name='mark',
            field=models.CharField(default='', max_length=50, verbose_name='标记'),
        ),
    ]
