# Generated by Django 6.1 on 2026-09-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0017_sectorlist_hide_alter_sectorlist_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectorlist',
            name='sort_order',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
        migrations.AlterField(
            model_name='focusstock',
            name='sort_order',
            field=models.IntegerField(default=1, verbose_name='排序'),
        ),
    ]
