# Generated by Django 6.1 on 2026-09-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0018_sectorlist_sort_order_alter_focusstock_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectorlist',
            name='sort_order',
        ),
    ]
