# Generated by Django 6.1 on 2026-09-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0019_remove_sectorlist_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilterGlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled_boards', models.CharField(blank=True, default='', help_text='逗号分隔的板块 key，空=全部启用', max_length=100, verbose_name='启用板块')),
                ('exclude_st', models.CharField(blank=True, default='', help_text='1=样本中排除名称含 ST 的股票', max_length=2, verbose_name='排除ST')),
            ],
            options={
                'verbose_name': '筛选全局配置',
                'verbose_name_plural': '筛选全局配置',
                'db_table': 'models_filter_global_config',
            },
        ),
        migrations.AddField(
            model_name='stocklist',
            name='hide',
            field=models.CharField(default='', max_length=50, verbose_name='隐藏'),
        ),
        migrations.AddField(
            model_name='stocklist',
            name='mark',
            field=models.CharField(default='', max_length=50, verbose_name='标记'),
        ),
        migrations.CreateModel(
            name='FilterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='任务名称')),
                ('source', models.CharField(choices=[('stock', '全量样本'), ('task', '上次结果')], db_index=True, default='stock', max_length=10, verbose_name='样本来源')),
                ('conditions', models.TextField(blank=True, default='[]', verbose_name='筛选条件(JSON)')),
                ('stock_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='models.filtertask', verbose_name='上级筛选')),
            ],
            options={
                'verbose_name': '筛选任务',
                'verbose_name_plural': '筛选任务',
                'db_table': 'models_filter_task',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FilterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='代码')),
                ('name', models.CharField(default='', max_length=50, verbose_name='名称')),
                ('market', models.CharField(default='SH', max_length=10, verbose_name='市场')),
                ('cat', models.CharField(default='stock', max_length=10, verbose_name='类别')),
                ('mark', models.CharField(blank=True, choices=[('', '无标记'), ('1', '优先股'), ('2', '潜力股')], default='', max_length=2, verbose_name='标记')),
                ('hide', models.CharField(blank=True, default='', help_text='1=已隐藏，同步 StockList.hide', max_length=2, verbose_name='隐藏')),
                ('sort_order', models.IntegerField(default=1, verbose_name='排序')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='models.filtertask', verbose_name='所属筛选')),
            ],
            options={
                'verbose_name': '筛选结果',
                'verbose_name_plural': '筛选结果',
                'db_table': 'models_filter_result',
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['task', 'mark'], name='models_filt_task_id_99063c_idx')],
                'unique_together': {('task', 'code', 'market')},
            },
        ),
    ]
