# Generated by Django 6.1 on 2026-09-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0020_filterglobalconfig_stocklist_hide_stocklist_mark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtertask',
            name='status',
            field=models.CharField(choices=[('running', '运行中'), ('done', '已完成')], db_index=True, default='done', max_length=10, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='filterglobalconfig',
            name='exclude_st',
            field=models.CharField(blank=True, default='1', help_text='1=样本中排除名称含 ST 的股票', max_length=2, verbose_name='排除ST'),
        ),
    ]
