# Generated by Django 6.1 on 2026-09-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0021_filtertask_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filterglobalconfig',
            name='default_task_id',
            field=models.IntegerField(blank=True, default=0, help_text='筛选清单默认显示的任务ID，0=最新任务', verbose_name='默认筛选任务ID'),
        ),
    ]
