# Generated by Django 6.1 on 2026-09-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0022_filterglobalconfig_default_task_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectorlist',
            name='hide',
        ),
        migrations.CreateModel(
            name='StockSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(db_index=True, max_length=20)),
                ('stock_market', models.CharField(max_length=10)),
                ('sector_code', models.CharField(db_index=True, max_length=20)),
                ('sector_market', models.CharField(default='SW', max_length=10)),
            ],
            options={
                'db_table': 'models_stock_sector',
                'unique_together': {('stock_code', 'stock_market', 'sector_code', 'sector_market')},
            },
        ),
    ]
