# Generated by Django 6.1 on 2026-09-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0023_remove_sectorlist_hide_stocksector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashhistory',
            name='reason',
        ),
        migrations.AddField(
            model_name='cashconfig',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='投资收益'),
        ),
        migrations.AddField(
            model_name='cashconfig',
            name='risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='风险资金'),
        ),
        migrations.AddField(
            model_name='cashhistory',
            name='event',
            field=models.CharField(choices=[('deposit', '存入资金'), ('withdraw', '取出资金'), ('buy', '买入股票'), ('sell', '卖出股票'), ('adjust', '手动调整'), ('dividend', '分红')], default='adjust', max_length=20, verbose_name='事项'),
        ),
        migrations.AddField(
            model_name='cashhistory',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='收益'),
        ),
        migrations.AlterField(
            model_name='cashconfig',
            name='total',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=14, verbose_name='资产'),
        ),
        migrations.AlterField(
            model_name='cashhistory',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='正数=增加, 负数=减少', max_digits=14, verbose_name='变动'),
        ),
        migrations.AlterField(
            model_name='cashhistory',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='股票'),
        ),
        migrations.AlterField(
            model_name='cashhistory',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='资产'),
        ),
    ]
