# Generated by Django 6.1 on 2026-09-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0025_alter_cashhistory_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashconfig',
            name='available',
        ),
        migrations.AddField(
            model_name='cashconfig',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=14, verbose_name='风险额度'),
        ),
        migrations.AddField(
            model_name='transorder',
            name='risk_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='风险资金占用'),
        ),
    ]
