# Generated by Django 6.1 on 2026-09-25 10:01

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0026_remove_cashconfig_available_cashconfig_allowance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashconfig',
            name='allowance',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=14, verbose_name='风险额度'),
        ),
        migrations.AlterField(
            model_name='cashconfig',
            name='commission_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='最低佣金'),
        ),
        migrations.AlterField(
            model_name='cashconfig',
            name='commission_ratio',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.000085'), max_digits=8, verbose_name='佣金费率'),
        ),
        migrations.AlterField(
            model_name='cashconfig',
            name='stamp_buy_ratio',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8, verbose_name='印花税率(买入)'),
        ),
        migrations.AlterField(
            model_name='cashconfig',
            name='stamp_sell_ratio',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.0005'), max_digits=8, verbose_name='印花税率(卖出)'),
        ),
        migrations.AlterField(
            model_name='cashconfig',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='股票'),
        ),
    ]
