# Generated by Django 6.1 on 2026-09-25 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0027_alter_cashconfig_allowance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashhistory',
            old_name='amount',
            new_name='change',
        ),
    ]
