# Generated by Django 6.1 on 2026-09-25 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0028_rename_amount_cashhistory_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('buy', '买入'), ('sell', '卖出'), ('edit', '编辑')], default='buy', max_length=10, verbose_name='操作类型')),
                ('intent', models.CharField(choices=[('B', '买入'), ('S', '卖出')], default='B', max_length=1, verbose_name='交易方向')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='操作日期')),
                ('price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='成交价格')),
                ('qty', models.IntegerField(default=0, verbose_name='成交数量')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='成交金额')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='交易费用')),
                ('target_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='目标价格')),
                ('stop_price', models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='止损价格')),
                ('comments', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='models.transorder', verbose_name='所属交易')),
            ],
            options={
                'verbose_name': '交易历史',
                'verbose_name_plural': '交易历史',
                'db_table': 'models_trans_history',
                'ordering': ['date', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='TransDeal',
        ),
    ]
