# Generated by Django 6.1 on 2026-09-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0029_transhistory_delete_transdeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transorder',
            name='position_cost_no_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='不含手续费持仓成本'),
        ),
    ]
