# Generated by Django 6.1 on 2026-09-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0030_transorder_position_cost_no_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transhistory',
            name='avg_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='持仓均价'),
        ),
        migrations.AddField(
            model_name='transhistory',
            name='position_qty',
            field=models.IntegerField(default=0, verbose_name='持仓数量'),
        ),
        migrations.AddField(
            model_name='transhistory',
            name='profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='账面收益'),
        ),
        migrations.AddField(
            model_name='transhistory',
            name='risk_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='风险资金'),
        ),
        migrations.AddField(
            model_name='transhistory',
            name='win_ratio',
            field=models.IntegerField(default=0, verbose_name='盈利机会'),
        ),
    ]
