# Generated by Django 6.1 on 2026-09-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0031_transhistory_avg_cost_transhistory_position_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transorder',
            name='intent',
            field=models.CharField(choices=[('B', '买入'), ('S', '卖出')], default='B', max_length=1, verbose_name='交易方向'),
        ),
    ]
