# Generated by Django 6.1 on 2026-09-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0032_transorder_intent'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filterglobalconfig',
            table='models_filter_config',
        ),
    ]
