# Generated by Django 6.1 on 2026-09-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0033_alter_filterglobalconfig_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='focusstock',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='transorder',
            name='comments',
        ),
    ]
