# Generated by Django 6.1 on 2026-09-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0034_remove_focusstock_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transhistory',
            name='avg_cost_no_fee',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='不含费持仓均价'),
        ),
    ]
