# Generated by Django 6.1 on 2026-09-26 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0035_transhistory_avg_cost_no_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='transorder',
            name='sold_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='含手续费累计卖出成本'),
        ),
        migrations.AddField(
            model_name='transorder',
            name='win_ratio',
            field=models.IntegerField(default=0, verbose_name='盈利机会'),
        ),
    ]
