# Generated by Django 6.1 on 2026-09-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0036_transorder_sold_cost_transorder_win_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='transorder',
            name='position_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='含手续费持仓成本'),
        ),
    ]
