# Generated by Django 6.1 on 2026-09-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0037_transorder_position_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashhistory',
            name='profit',
        ),
        migrations.AddField(
            model_name='cashhistory',
            name='current_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='本次收益'),
        ),
        migrations.AddField(
            model_name='cashhistory',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='累计收益'),
        ),
    ]
