# Generated by Django 6.1 on 2026-09-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0038_remove_cashhistory_profit_cashhistory_current_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashhistory',
            name='risk',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='风险资金'),
        ),
        migrations.AlterField(
            model_name='cashhistory',
            name='event',
            field=models.CharField(choices=[('deposit', '存入资金'), ('withdraw', '取出资金'), ('buy', '买入股票'), ('sell', '卖出股票'), ('dividend', '分红'), ('adjust', '调整计划')], default='deposit', max_length=20, verbose_name='事项'),
        ),
    ]
