# Generated by Django 6.1 on 2026-09-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0039_cashhistory_risk_alter_cashhistory_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filterglobalconfig',
            name='default_task_id',
            field=models.IntegerField(blank=True, default=-1, help_text='筛选清单默认显示的任务ID，-1=无任务', verbose_name='默认筛选任务ID'),
        ),
    ]
