# Generated by Django 6.1 on 2026-09-27 10:57

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0040_alter_filterglobalconfig_default_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_ratio', models.DecimalField(decimal_places=6, default=Decimal('0.000085'), max_digits=8, verbose_name='佣金费率')),
                ('commission_min', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='最低佣金')),
                ('stamp_buy_ratio', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=8, verbose_name='印花税率(买入)')),
                ('stamp_sell_ratio', models.DecimalField(decimal_places=6, default=Decimal('0.0005'), max_digits=8, verbose_name='印花税率(卖出)')),
                ('dividend_tax_long', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6, verbose_name='分红税(>1年)')),
                ('dividend_tax_mid', models.DecimalField(decimal_places=4, default=Decimal('0.1'), max_digits=6, verbose_name='分红税(1月~1年)')),
                ('dividend_tax_short', models.DecimalField(decimal_places=4, default=Decimal('0.2'), max_digits=6, verbose_name='分红税(<1月)')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='更新日期')),
            ],
            options={
                'verbose_name': '全站参数设置',
                'verbose_name_plural': '全站参数设置',
                'db_table': 'models_web_setting',
            },
        ),
        migrations.RemoveField(
            model_name='cashconfig',
            name='commission_min',
        ),
        migrations.RemoveField(
            model_name='cashconfig',
            name='commission_ratio',
        ),
        migrations.RemoveField(
            model_name='cashconfig',
            name='stamp_buy_ratio',
        ),
        migrations.RemoveField(
            model_name='cashconfig',
            name='stamp_sell_ratio',
        ),
        migrations.AlterField(
            model_name='transhistory',
            name='action',
            field=models.CharField(choices=[('buy', '买入'), ('sell', '卖出'), ('edit', '编辑'), ('dividend', '分红')], default='buy', max_length=10, verbose_name='操作类型'),
        ),
        migrations.CreateModel(
            name='DividendRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, verbose_name='股票代码')),
                ('name', models.CharField(max_length=50, verbose_name='股票名称')),
                ('market', models.CharField(default='SH', max_length=10, verbose_name='股票市场')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='分红日期')),
                ('dividend_type', models.CharField(choices=[('cash', '现金分红'), ('bonus', '送股转增')], default='cash', max_length=10, verbose_name='分红类型')),
                ('per_share', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='每股分红(税前)')),
                ('bonus_ratio', models.DecimalField(decimal_places=4, default=0, max_digits=8, verbose_name='送股比例')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='税前分红总额')),
                ('qty_change', models.IntegerField(default=0, verbose_name='持仓变化数量')),
                ('remark', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='models.transorder', verbose_name='所属交易')),
            ],
            options={
                'verbose_name': '分红记录',
                'verbose_name_plural': '分红记录',
                'db_table': 'models_dividend_record',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
